version: '3'
services:
  init:
    command: initNode
    build: .
    volumes:
      - ../config:/root/.gaia/
      - ./app.toml:/root/.gaia/config/app.toml
      - ./config.toml:/root/.gaia/config/config.toml
      - ./genesis.json:/root/.gaia/config/genesis.json

  gaia:
    command: start
    build: .
    volumes:
      - ../config:/root/.gaia/
      - ./app.toml:/root/.gaia/config/app.toml
      - ./config.toml:/root/.gaia/config/config.toml
      - ./genesis.json:/root/.gaia/config/genesis.json
