version: '3'
services:
  gaia:
    command: start
    build: .
    volumes:
      - ../config:/root/.gaia/
      - ./app.toml:/root/.gaia/config/app.toml
      - ./config.toml:/root/.gaia/config/config.toml
      - ./genesis.json:/root/.gaia/config/genesis.json
      - ./addrbook.json:/root/.gaia/config/addrbook.json
